Make the app single page again
WhiteboardLiveCoding/WebUI pull request #10
Opened 2017-11-16 09:31 UTC by SuNaden

Hola,

So this is a MR to make the whole webapp work on a single page. All of this is to avoid the cross scripting that was introduced and to not rely on page rendering but rather to rely on displaying the message using javascript DOM updates from the JSON response.

This means we need just one `index.html` and we handle the DOM change with javascript `hide` and `show`.

Also note that this was not tested using Azure but with my own dummy responses.

Some known issues:
1. When you upload picture and we do OCR, you need to click on codemirror editor (something to do with focusing on the dom element)
2. I could not get the image displaying to work, but I think it is only about messing with the key from json correctly (also drawing code should be moved)
3. I had to remove code resubmission voice control because it was being executed like every few seconds, can be easily added back

2017-11-16 11:56 UTC, PaulSonOfLars requested changes

2017-11-16 11:56 UTC, PaulSonOfLars commented on application.py
> +            ar = r.get('ar',"")
Your rebase jsut undoes everything we wrote the other day.

2017-11-16 12:30 UTC, SuNaden commented
@PaulSonOfLars Sorry for that, it was because of the rebase now it should be okay.
I also got the image displaying to work

2017-11-17 09:58 UTC, martinzlocha approved these changes

2017-11-17 10:53 UTC, merged